#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]

PAPER_DATASETS = (
    "Sports_and_Outdoors",
    "Beauty",
    "Toys_and_Games",
    "CDs_and_Vinyl",
)
EXTRA_DATASETS = (
    "Video_Games",
    "Pet_Supplies",
)

RPG_CONFIGS = {
    "Sports_and_Outdoors": REPO_ROOT / "configs/rpg/repro/sports_and_outdoors.yaml",
    "Beauty": REPO_ROOT / "configs/rpg/repro/beauty.yaml",
    "Toys_and_Games": REPO_ROOT / "configs/rpg/repro/toys_and_games.yaml",
    "CDs_and_Vinyl": REPO_ROOT / "configs/rpg/repro/cds_and_vinyl.yaml",
    "Video_Games": REPO_ROOT / "configs/rpg/new_datasets/video_games.yaml",
    "Pet_Supplies": REPO_ROOT / "configs/rpg/new_datasets/pet_supplies.yaml",
}

SASREC_SUMMARY_DIR = REPO_ROOT / "artifacts/sasrec/data"
RPG_MODEL_CONFIG = REPO_ROOT / "third_party/genrec/models/RPG/config.yaml"
SASREC_MODEL_CONFIG = REPO_ROOT / "models/sasrec/config.yaml"
PARAM_MATCHED_DIR = REPO_ROOT / "configs/sasrec/param_matched"


def load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def count_rpg_params(config: dict) -> tuple[int, int, int]:
    """Match third_party/genrec/models/RPG/model.py."""
    n_embd = int(config["n_embd"])
    n_layer = int(config["n_layer"])
    n_inner = int(config["n_inner"])
    n_codebook = int(config["n_codebook"])
    codebook_size = int(config["codebook_size"])
    max_positions = int(config["max_item_seq_len"])

    vocab_size = n_codebook * codebook_size + 2
    token_embedding_params = vocab_size * n_embd
    position_embedding_params = max_positions * n_embd

    # Hugging Face GPT2Block: attention, MLP, and two layer norms.
    block_params = 4 * n_embd * n_embd + 2 * n_embd * n_inner + 9 * n_embd + n_inner
    final_layer_norm_params = 2 * n_embd

    # RPG adds one ResBlock prediction head per semantic-ID digit.
    pred_head_params = n_codebook * (n_embd * n_embd + n_embd)

    total = (
        token_embedding_params
        + position_embedding_params
        + n_layer * block_params
        + final_layer_norm_params
        + pred_head_params
    )
    return token_embedding_params, total - token_embedding_params, total


def count_sasrec_params(config: dict, n_items: int) -> int:
    """Match models/sasrec/model.py and models/sasrec/modules.py."""
    hidden_size = int(config["hidden_size"])
    max_seq_length = int(config["max_seq_length"])
    n_layers = int(config["num_hidden_layers"])

    item_size = n_items + 2  # PAD id 0 and mask id max_item + 1.
    item_embedding_params = item_size * hidden_size
    position_embedding_params = max_seq_length * hidden_size
    embedding_layer_norm_params = 2 * hidden_size

    # Per SASRec layer: self-attention + feed-forward + their layer norms.
    layer_params = 12 * hidden_size * hidden_size + 13 * hidden_size
    return (
        item_embedding_params
        + position_embedding_params
        + embedding_layer_norm_params
        + n_layers * layer_params
    )


def find_sasrec_hidden_size(
    target_params: int,
    config: dict,
    n_items: int,
    max_hidden_size: int,
) -> tuple[int, int, float]:
    n_heads = int(config["num_attention_heads"])
    best_hidden_size = n_heads
    best_params = count_sasrec_params({**config, "hidden_size": best_hidden_size}, n_items)
    best_error = abs(best_params - target_params) / target_params

    for hidden_size in range(n_heads, max_hidden_size + 1, n_heads):
        params = count_sasrec_params({**config, "hidden_size": hidden_size}, n_items)
        error = abs(params - target_params) / target_params
        if error < best_error:
            best_hidden_size = hidden_size
            best_params = params
            best_error = error

    return best_hidden_size, best_params, best_error


def format_int(value: int | None) -> str:
    return "-" if value is None else f"{value:,}"


def dataset_slug(dataset: str) -> str:
    return dataset.lower()


def write_sasrec_overlay(path: Path, row: dict, config: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = (
        f"# Auto-generated by scripts/count_model_params.py.\n"
        f"# Matches SASRec params to RPG for {row['dataset']}.\n"
        f"# RPG params: {row['rpg_total']}\n"
        f"# Matched SASRec params: {row['matched_sasrec_total']}\n"
        f"# Relative error: {row['matched_error']:.4%}\n"
        f"run_id: sasrec_param_matched_{dataset_slug(row['dataset'])}\n"
        f"hidden_size: {row['matched_hidden_size']}\n"
        f"num_hidden_layers: {int(config['num_hidden_layers'])}\n"
        f"num_attention_heads: {int(config['num_attention_heads'])}\n"
    )
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Print trainable parameter counts for RPG and SASRec dataset presets."
    )
    parser.add_argument(
        "--all-configured",
        action="store_true",
        help="Also include configured datasets whose prepared SASRec summaries may be missing.",
    )
    parser.add_argument(
        "--rpg-n-codebook",
        type=int,
        default=None,
        help="Override RPG n_codebook/m before counting, useful for the RPG m sweep.",
    )
    parser.add_argument(
        "--max-hidden-size",
        type=int,
        default=2048,
        help="Maximum SASRec hidden_size to search when matching RPG params.",
    )
    parser.add_argument(
        "--write-sasrec-param-matched-configs",
        action="store_true",
        help="Write SASRec overlay YAMLs under configs/sasrec/param_matched/.",
    )
    args = parser.parse_args()

    datasets = PAPER_DATASETS + (EXTRA_DATASETS if args.all_configured else ())
    rpg_base = load_yaml(RPG_MODEL_CONFIG)
    sasrec_config = load_yaml(SASREC_MODEL_CONFIG)

    rows = []
    for dataset in datasets:
        rpg_config = dict(rpg_base)
        rpg_config.update(load_yaml(RPG_CONFIGS[dataset]))
        if args.rpg_n_codebook is not None:
            rpg_config["n_codebook"] = args.rpg_n_codebook
        rpg_emb, rpg_non_emb, rpg_total = count_rpg_params(rpg_config)

        summary_path = SASREC_SUMMARY_DIR / dataset / "summary.json"
        n_items = None
        sasrec_total = None
        note = ""
        if summary_path.is_file():
            with summary_path.open("r", encoding="utf-8") as handle:
                summary = json.load(handle)
            n_items = int(summary["n_items"])
            sasrec_total = count_sasrec_params(sasrec_config, n_items)
            matched_hidden_size, matched_sasrec_total, matched_error = find_sasrec_hidden_size(
                rpg_total,
                sasrec_config,
                n_items,
                args.max_hidden_size,
            )
        else:
            note = f"missing {summary_path.relative_to(REPO_ROOT)}"
            matched_hidden_size = None
            matched_sasrec_total = None
            matched_error = None

        rows.append(
            {
                "dataset": dataset,
                "n_items": n_items,
                "rpg_m": int(rpg_config["n_codebook"]),
                "rpg_embedding": rpg_emb,
                "rpg_non_embedding": rpg_non_emb,
                "rpg_total": rpg_total,
                "sasrec_total": sasrec_total,
                "ratio": None if sasrec_total is None else rpg_total / sasrec_total,
                "matched_hidden_size": matched_hidden_size,
                "matched_sasrec_total": matched_sasrec_total,
                "matched_error": matched_error,
                "note": note,
            }
        )

    headers = (
        "dataset",
        "items",
        "RPG m",
        "RPG emb",
        "RPG non-emb",
        "RPG total",
        "SASRec total",
        "RPG/SASRec",
        "matched h",
        "matched SASRec",
        "match err",
        "note",
    )
    print(" | ".join(headers))
    print(" | ".join("-" * len(header) for header in headers))
    for row in rows:
        ratio = "-" if row["ratio"] is None else f"{row['ratio']:.2f}x"
        matched_error = "-" if row["matched_error"] is None else f"{row['matched_error']:.2%}"
        print(
            " | ".join(
                (
                    row["dataset"],
                    format_int(row["n_items"]),
                    str(row["rpg_m"]),
                    format_int(row["rpg_embedding"]),
                    format_int(row["rpg_non_embedding"]),
                    format_int(row["rpg_total"]),
                    format_int(row["sasrec_total"]),
                    ratio,
                    format_int(row["matched_hidden_size"]),
                    format_int(row["matched_sasrec_total"]),
                    matched_error,
                    row["note"],
                )
            )
        )

    if args.write_sasrec_param_matched_configs:
        for row in rows:
            if row["matched_hidden_size"] is None:
                continue
            output_path = PARAM_MATCHED_DIR / f"{dataset_slug(row['dataset'])}.yaml"
            write_sasrec_overlay(output_path, row, sasrec_config)
            print(f"wrote {output_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
